### ISSUE TITLE
Not compatible with Citizens

### ISSUE THREAD

**Issue by ShallowAi** [Nothing00Official/MainMC#1]
[14:05:37] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to MainMC v3.4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:620) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:523) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:652) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1415) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:860) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:888) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:773) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:629) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:180) ~[?:?]
	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1028) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1397) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1724) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Spigot_1.12.2.jar:git-Paper-1615]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at mainmc.nothing00.functions.User.hasKeyword(User.java:901) ~[?:?]
	at mainmc.nothing00.functions.User.isLocked(User.java:921) ~[?:?]
	at mainmc.listener.DamageEvent.onDamage(DamageEvent.java:79) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Spigot_1.12.2.jar:git-Paper-1615]
	... 27 more

**Comment by Nothing00Official** [comment]
This has been resolved in new version 3.4.5
