### ISSUE TITLE
[SQLITE_BUSY]  The database file is locked (database is locked)

### ISSUE THREAD

**Issue by erposse90** [Nothing00Official/MainMC#13]
The plugin worked fine, then it didn't allow me to do the transaction anymore and the console gave this error, how can I fix it ??
ps 
the only changes I made to the server were to switch to offline mode and add buycraft

below the complete error:

26.12 17:08:25 [Server] Server thread/WARN []: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
26.12 17:08:25 [Server] Server thread/WARN []: at org.sqlite.core.DB.newSQLException(DB.java:909)
26.12 17:08:25 [Server] Server thread/WARN []: at org.sqlite.core.DB.newSQLException(DB.java:921)
26.12 17:08:25 [Server] Server thread/WARN []: at org.sqlite.core.DB.execute(DB.java:822)
26.12 17:08:25 [Server] Server thread/WARN []: at org.sqlite.core.DB.executeUpdate(DB.java:863)
26.12 17:08:25 [Server] Server thread/WARN []: at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
26.12 17:08:25 [Server] Server thread/WARN []: at mainmc.folders.DataBase.setBalance(DataBase.java:323)
26.12 17:08:25 [Server] Server thread/WARN []: at mainmc.nothing00.utils.Economy.removeMoney(Economy.java:134)
26.12 17:08:25 [Server] Server thread/WARN []: at mainmc.economy.vault.VaultManager.withdrawPlayer(VaultManager.java:273)
26.12 17:08:25 [Server] Server thread/WARN []: at mainmc.economy.EconomyAPI.setMoney(EconomyAPI.java:26)
26.12 17:08:25 [Server] Server thread/WARN []: at mainmc.nothing00.utils.Economy.setMoney(Economy.java:120)
26.12 17:08:25 [Server] Server thread/WARN []: at mainmc.commands.EconomyCommand.onCommand(EconomyCommand.java:124)
26.12 17:08:25 [Server] Server thread/WARN []: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
26.12 17:08:25 [Server] Server thread/WARN []: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
26.12 17:08:25 [Server] Server thread/WARN []: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1615)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1450)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
26.12 17:08:25 [Server] Server thread/WARN []: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
26.12 17:08:25 [Server] Server thread/WARN []: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.util.Util.func_181617_a(SourceFile:46)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
26.12 17:08:25 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
26.12 17:08:25 [Server] Server thread/WARN []: at java.lang.Thread.run(Thread.java:748)
26.12 17:08:28 [Server] Server thread/WARN []: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
26.12 17:08:28 [Server] Server thread/WARN []: at org.sqlite.core.DB.newSQLException(DB.java:909)
26.12 17:08:28 [Server] Server thread/WARN []: at org.sqlite.core.DB.newSQLException(DB.java:921)
26.12 17:08:28 [Server] Server thread/WARN []: at org.sqlite.core.DB.execute(DB.java:822)
26.12 17:08:28 [Server] Server thread/WARN []: at org.sqlite.core.DB.executeUpdate(DB.java:863)
26.12 17:08:28 [Server] Server thread/WARN []: at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
26.12 17:08:28 [Server] Server thread/WARN []: at mainmc.folders.DataBase.setBalance(DataBase.java:323)
26.12 17:08:28 [Server] Server thread/WARN []: at mainmc.nothing00.utils.Economy.addMoney(Economy.java:108)
26.12 17:08:28 [Server] Server thread/WARN []: at mainmc.economy.vault.VaultManager.depositPlayer(VaultManager.java:106)
26.12 17:08:28 [Server] Server thread/WARN []: at mainmc.economy.EconomyAPI.setMoney(EconomyAPI.java:27)
26.12 17:08:28 [Server] Server thread/WARN []: at mainmc.nothing00.utils.Economy.setMoney(Economy.java:120)
26.12 17:08:28 [Server] Server thread/WARN []: at mainmc.commands.EconomyCommand.onCommand(EconomyCommand.java:124)
26.12 17:08:28 [Server] Server thread/WARN []: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
26.12 17:08:28 [Server] Server thread/WARN []: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
26.12 17:08:28 [Server] Server thread/WARN []: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1615)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1450)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
26.12 17:08:28 [Server] Server thread/WARN []: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
26.12 17:08:28 [Server] Server thread/WARN []: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.util.Util.func_181617_a(SourceFile:46)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
26.12 17:08:28 [Server] Server thread/WARN []: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)

**Comment by erposse90** [comment]
while we're at it, how do I make the kit cmd run console commands ??
can you give me an example of correct syntax?
