### ISSUE TITLE
SQLite problems

### ISSUE THREAD

**Issue by KarmaDeb** [Nothing00Official/MainMC#4]
Hi, I love your plugin, it's really good and I know it's in beta, so I hope these bug reports help you to improve even more your plugin:

Sometimes, SQLite gives connection problems

```
java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
[12:48:40 WARN]:        at org.sqlite.DB.newSQLException(DB.java:383)
[12:48:40 WARN]:        at org.sqlite.DB.newSQLException(DB.java:387)
[12:48:40 WARN]:        at org.sqlite.DB.execute(DB.java:339)
[12:48:40 WARN]:        at org.sqlite.DB.executeUpdate(DB.java:363)
[12:48:40 WARN]:        at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[12:48:40 WARN]:        at mainmc.folders.DataBase.setLockAccount(DataBase.java:221)
[12:48:40 WARN]:        at mainmc.nothing00.functions.User.setKeyword(User.java:905)
[12:48:40 WARN]:        at mainmc.commands.LockAccountCommand.onCommand(LockAccountCommand.java:34)
[12:48:40 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:48:40 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[12:48:40 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12:48:40 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:48:40 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[12:48:40 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[12:48:40 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:48:45 WARN]: java.sql.SQLException: cannot commit transaction - SQL statements in progress
[12:48:45 WARN]:        at org.sqlite.DB.throwex(DB.java:370)
[12:48:45 WARN]:        at org.sqlite.DB.ensureAutoCommit(DB.java:435)
[12:48:45 WARN]:        at org.sqlite.DB.execute(DB.java:332)
[12:48:45 WARN]:        at org.sqlite.Stmt.exec(Stmt.java:65)
[12:48:45 WARN]:        at org.sqlite.Stmt.executeQuery(Stmt.java:122)
[12:48:45 WARN]:        at mainmc.folders.DataBase.isJailed(DataBase.java:760)
[12:48:45 WARN]:        at mainmc.nothing00.functions.User.isJailed(User.java:881)
[12:48:45 WARN]:        at mainmc.listener.CommandEvent.onChat(CommandEvent.java:65)
[12:48:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:48:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:48:45 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:48:45 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[12:48:45 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[12:48:45 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[12:48:45 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:48:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[12:48:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1181)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12:48:45 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:48:45 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[12:48:45 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[12:48:45 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by KarmaDeb** [comment]
I forgot to say, the /gamemode <GameMode> <player> command is not working

![image](https://user-images.githubusercontent.com/54160333/85708418-6e723a80-b6e4-11ea-8db7-aa60fb1f9ef7.png)

I have to use /gmc, but If I want to change other player gamemode, I can't do it
