### ISSUE TITLE
Crashes my server and spams console

### ISSUE THREAD

**Issue by officialMozart** [Nothing00Official/MainMC#6]
Whenever i start my server with mainmc it crashes my server and spamms this error
Running paper 1.15.2 378
Error:
>.... [12:24:45 ERROR]: Could not pass event EntityDamageByBlockEvent to MainMC v3.6
java.lang.NullPointerException: null
at mainmc.nothing00.functions.User.hasKeyword(User.java:901) ~[?:?]
at mainmc.nothing00.functions.User.isLocked(User.java:921) ~[?:?]
at mainmc.listener.DamageEvent.onDamage(DamageEvent.java:34) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-378]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:240) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:899) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:851) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1040) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:878) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:780) ~[patched_1.15.2.jar:git-Paper-378]
at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:141) ~[?:?]
at net.minecraft.server.v1_15_R1.EntityLiving.af(EntityLiving.java:1860) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.Entity.doVoidDamage(Entity.java:591) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.Entity.performVoidDamage(Entity.java:511) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.Entity.entityBaseTick(Entity.java:494) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:244) ~[patched_1.15.2.jar:git-Paper-378]
at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.playerTick(EntityHumanNPC.java:348) ~[?:?]
at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.playerTick(NMSImpl.java:950) ~[?:?]
at net.citizensnpcs.util.NMS.playerTick(NMS.java:340) ~[?:?]
at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by RedstonedLife** [comment]
@SenkuUzumaki Could you provide more info?
Like:
What plugins are you running except MainMC?
`latest.log` or the `.log` file that contains the full errors.
Cause it may spam your console. But not all of the spam might be 1 error, It might be a few.
